spring:
  datasource:
    url: jdbc:postgresql://dpg-d4mrqdkhg0os73c3pt00-a.oregon-postgres.render.com:5432/onlinebusdb_8pl8
    username: onlinebusdb_8pl8_user
    password: qhvau5oLkvSQcizA3VHMC5bvYIlSWK3x

  profiles:
    active: dev

  jackson:
    serialization:
      indent_output: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: guguu957@gmail.com
    password: dqrz qrjd byxm hwqq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.debug: true

server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

app:
  pagination:
    default-page: 0
    default-size: 10
    max-size: 100

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xypha.OnlineBus.Buses.Entity

google:
  api:
    key: AIzaSyCqM6amY2SHdgtd8btmWztV5pDV8y3K48s