spring:
  datasource:
    url: jdbc:postgresql://dpg-d4mrqdkhg0os73c3pt00-a.oregon-postgres.render.com:5432/onlinebusdb_8pl8
    username: onlinebusdb_8pl8_user
    password: qhvau5oLkvSQcizA3VHMC5bvYIlSWK3x
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000
      initialization-fail-timeout: 0

  profiles:
    active: dev

aws:
  accessKeyId: AKIA4EKNTTICRGWWWYNZ
  secretAccessKey: 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
  region: ap-southeast-1
  ses:
    sender-email: guguu957@gmail.com

logging:
  level:
    software.amazon.awssdk.services.ses: DEBUG



server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

app:
  pagination:
    default-page: 0
    default-size: 10
    max-size: 100

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xypha.OnlineBus.Buses.Entity

google:
  api:
    key: AIzaSyBZbqUF_6LVPCt2vzG_1igZ-g0sYMKMAu4